export const schema = {
  models: {
    SpeakerVoiceEmotion: {
      name: "SpeakerVoiceEmotion",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        timestamp: {
          name: "timestamp",
          isArray: false,
          type: "AWSTimestamp",
          isRequired: true,
          attributes: [],
        },
        score: {
          name: "score",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        neutral: {
          name: "neutral",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        happy: {
          name: "happy",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        sad: {
          name: "sad",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        angry: {
          name: "angry",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        fearful: {
          name: "fearful",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        disgusted: {
          name: "disgusted",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        surprised: {
          name: "surprised",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        meetingID: {
          name: "meetingID",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "SpeakerVoiceEmotions",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "key",
          properties: {
            name: "byMeeting",
            fields: ["meetingID"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                operations: ["read", "create", "update", "delete"],
                identityClaim: "cognito:username",
              },
            ],
          },
        },
      ],
    },
    PublicMeetingInfo: {
      name: "PublicMeetingInfo",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        startedAt: {
          name: "startedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        stoppedAt: {
          name: "stoppedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        owner: {
          name: "owner",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "PublicMeetingInfos",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                operations: ["read", "create", "update", "delete"],
                identityClaim: "cognito:username",
              },
              {
                allow: "public",
                operations: ["read"],
                provider: "iam",
              },
            ],
          },
        },
      ],
    },
    Evaluation: {
      name: "Evaluation",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        owner: {
          name: "owner",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        publicmeetinginfoID: {
          name: "publicmeetinginfoID",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        code: {
          name: "code",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        cognitive_load: {
          name: "cognitive_load",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_1: {
          name: "distraction_1",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_2: {
          name: "distraction_2",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_3: {
          name: "distraction_3",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_4: {
          name: "distraction_4",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_5: {
          name: "distraction_5",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_6: {
          name: "distraction_6",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_7: {
          name: "distraction_7",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_8: {
          name: "distraction_8",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_9: {
          name: "distraction_9",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_10: {
          name: "distraction_10",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_11: {
          name: "distraction_11",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_12: {
          name: "distraction_12",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_13: {
          name: "distraction_13",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_14: {
          name: "distraction_14",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        distraction_15: {
          name: "distraction_15",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Evaluations",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                operations: ["read"],
                identityClaim: "cognito:username",
              },
              {
                allow: "public",
                operations: ["create"],
                provider: "iam",
              },
            ],
          },
        },
      ],
    },
    Meeting: {
      name: "Meeting",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        AudienceFaceExpressions: {
          name: "AudienceFaceExpressions",
          isArray: true,
          type: {
            model: "AudienceFaceExpression",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "meetingID",
          },
        },
        startedAt: {
          name: "startedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        stoppedAt: {
          name: "stoppedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        PublicMeetingInfo: {
          name: "PublicMeetingInfo",
          isArray: false,
          type: {
            model: "PublicMeetingInfo",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "BELONGS_TO",
            targetName: "meetingPublicMeetingInfoId",
          },
        },
        SpeakerVoiceEmotions: {
          name: "SpeakerVoiceEmotions",
          isArray: true,
          type: {
            model: "SpeakerVoiceEmotion",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "meetingID",
          },
        },
      },
      syncable: true,
      pluralName: "Meetings",
      attributes: [
        {
          type: "model",
          properties: {
            timestamps: {
              createdAt: "createdAt",
              updatedAt: "updatedAt",
            },
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                operations: ["read", "create", "update", "delete"],
                identityClaim: "cognito:username",
              },
            ],
          },
        },
      ],
    },
    AudienceFaceExpression: {
      name: "AudienceFaceExpression",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        timestamp: {
          name: "timestamp",
          isArray: false,
          type: "AWSTimestamp",
          isRequired: true,
          attributes: [],
        },
        score: {
          name: "score",
          isArray: false,
          type: "Float",
          isRequired: true,
          attributes: [],
        },
        surprised: {
          name: "surprised",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        happy: {
          name: "happy",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        neutral: {
          name: "neutral",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        sad: {
          name: "sad",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        disgusted: {
          name: "disgusted",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        fearful: {
          name: "fearful",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        angry: {
          name: "angry",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
        meetingID: {
          name: "meetingID",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "AudienceFaceExpressions",
      attributes: [
        {
          type: "model",
          properties: {
            timestamps: {
              createdAt: "createdAt",
              updatedAt: "updatedAt",
            },
          },
        },
        {
          type: "key",
          properties: {
            name: "byMeeting",
            fields: ["meetingID"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                operations: ["read", "create", "update", "delete"],
                identityClaim: "cognito:username",
              },
            ],
          },
        },
      ],
    },
  },
  enums: {},
  nonModels: {},
  version: "b4a462364268357288433ecf4530b393",
};
